### ISSUE TITLE
Copy & Paste menu not showing since iOS 13.5

### ISSUE THREAD

**Issue by KingKong5147** [hbang/NewTerm#39]
Hi , I am runnning a jailbroken iPhone 11 Pro on iOS 13.5 , the issue I am having is the copy and paste feature does not work I’ve tried on uncover and now on odyssey jailbreak still no luck any solution as I’m struggling to find one. Thanks :)

**Comment by KARZMA1** [comment]
I don't want you to send me

**Comment by KingKong5147** [comment]
I don’t want you to send me?... could you translate please

**Comment by KARZMA1** [comment]
I don't know

**Comment by KingKong5147** [comment]
Do me and yourself a favour and don’t write any more on this thread If you can’t help with the issue go away

**Comment by KARZMA1** [comment]
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂🖐🏻

**Comment by iAdam1n** [comment]
We're aware of this issue but it's super weird as it only happens for some people. For example, my SE has this issue but my 8 doesn't.

**Comment by KingKong5147** [comment]
Is there ideas as to what is causing it?.. any other on device terminal that allows copy and paste ?..

**Comment by iAdam1n** [comment]
Sadly not but we will investigate when we get time. In terms of others, I'm not sure.

**Comment by iiKulakov** [comment]
Not working for me too.
iPhone 11, 13.5 uncover

**Comment by TheAwesome98-Real** [comment]
Oh yeah that fully solved my problem, 3 finger tap revealed a copy paste menu. Thanks again!

**Comment by kirb** [comment]
Worked around in NewTerm 3 branch. It’s kinda annoying, you tap once to dismiss the keyboard, then selection works. Another tap brings the keyboard back.

The best explanation I can come up with is that iOS 13.4 or so changed how text selection works while the new iPad mouse support was being implemented. Previously, you could make selections in a non-editable text view without it becoming first responder. Now, that text view will refuse to handle any text selection gestures if not first responder, if a first responder already exists. That seems like an intentional change, which you can also reproduce in any other app that has two text views/fields on-screen. Only if you long press on the other non-focused text view will it respond to selection events - and even then, all you get is a floating cursor. That won’t start a text selection like the previous behavior was.

I want to likely redo this to be built on a custom collection view with a cell per row, selection handled completely custom by our code, so this will have to do for now.

**Comment by lccambiaghi** [comment]
Hi @kirb I have this issue on my iPad ios14. It would be amazing to have a solution to it and reading your comment gave me good hopes. Looking at the 3.0 milestone, it seems it will be a long way before it hits the Chariz repo. Would it be possible to do a 2.X patch release to get the fix out? It really sucks to not be able to copy text on a terminal. Thank you!!
