### ISSUE TITLE
[bug] when progress bars or terminal redraws are displayed they start to heavily bog down the terminal

### ISSUE THREAD

**Issue by nate-moo** [hbang/NewTerm#40]
Title, it’s very annoying when it does that for my workflow with the terminal. I have to constantly restart the tab to fix the lag. This can easily be reproduced with the command 
`curl parrot.live`
It will slowly start heavily lagging after about 5 seconds
If you need anything else feel free to ask

**Comment by TheAwesome98-Real** [comment]
I `cat`’d a .mov file (don’t ask why, I just did) and it froze the entire terminal. :|

**Comment by nate-moo** [comment]
Even doing a pip install will significantly slow down the terminal, I use python alot and sometimes on my phone so it's pretty annoying

**Comment by kirb** [comment]
Fixed-ish in 2.5.

The terminal rendering is still a bit slow, but this change helps a ton. Basically, before it would render changes as quickly as they come in from the terminal subprocess. That was a pretty bad approach because you can easily trigger any variety of terminal commands that spit out a lot of data as quickly as they possibly can (`yes`, `find /`, `cat blah.mov`). Now it only updates 60 times per second, which is more than fast enough (maybe even too much).
